version: "2"
services:
  app:
    restart: always
    build: .
    ports:
      - 10010:10010
    links:
      - database
    networks:
      - takatukanet
    depends_on:
      - database
    expose:
      - 10010
    environment:
      WAIT_HOSTS: database:27017
      MONGO_URL: mongodb://database/takatukazettel

  database:
    image: mongo
    # volumes:
    #   - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - takatukanet
      
networks:
  takatukanet:
    driver: bridge