version: "2"
services:
  takatukazettel:
    container_name: takatukazettel
    restart: always
    build: .
    ports:
      - 10010:10010
    links:
      - mongo
    networks:
      - takatukanet
    depends_on:
      - mongo
    expose:
      - 10010
    environment:
      WAIT_HOSTS: mongo:27017
      MONGO_URL: mongodb://mongo/takatukazettel
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - takatukanet
networks:
  takatukanet:
    driver: bridge